# Jekyll configuration

title: 山巅一寺一壶酒
description: Hello World!
author: limustc


# url is currently only used only for the RSS feed in feed.xml
url: http://www.limustc.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''


# Set this to your UA-# value, or '' to disable the block completely
# google analysis
gaaccount: 'UA-56110966-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'limustc'
comments: true

permalink: /:year/:month/:day/:title
paginate: 10

highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']